import express from 'express';
import {normalizeMessage} from './public/live-events.js';
import multer from 'multer';
import {WebSocketServer} from 'ws';
import {TikTokLiveConnection,WebcastEvent} from 'tiktok-live-connector';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),dataDir=process.env.DATA_DIR||path.join(root,'data');
await mkdir(path.join(dataDir,'media'),{recursive:true});
const defaults={chat:true,gift:true,follow:true,rate:1,volume:.8,voice:'',color:'#32d6b0',duration:5,alertPosition:'bottom',alertVolume:.7,followSound:'chime',giftSound:'sparkle',imageId:'',imageVisible:false,imageWidth:20,imageX:80,imageY:25,boardVisible:true,boardCount:3,boardPosition:'top-left'};
let rooms={};try{rooms=JSON.parse(await readFile(path.join(dataDir,'rooms.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e}
let writes=Promise.resolve();function save(){const content=JSON.stringify(rooms);writes=writes.catch(()=>{}).then(async()=>{await writeFile(path.join(dataDir,'rooms.tmp'),content);await rename(path.join(dataDir,'rooms.tmp'),path.join(dataDir,'rooms.json'))});return writes}
const key=()=>randomBytes(24).toString('hex'),connections=new Map(),tickets=new Map(),cooldowns=new Map();
function newRoom(){return {settings:{...defaults},revision:0,session:randomUUID(),username:'',events:[],media:[],latest:0}}
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'100kb'}));
app.use((req,res,next)=>{res.set('X-Content-Type-Options','nosniff');res.set('Referrer-Policy','no-referrer');if(!['GET','HEAD'].includes(req.method)&&req.headers.origin){try{if(new URL(req.headers.origin).host!==req.headers.host)return res.status(403).json({message:'คำขอไม่ได้มาจากเว็บนี้'})}catch{return res.sendStatus(403)}}next()});
function room(req,res,next){const token=req.query.token||req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('studio='))?.slice(7);if(token&&rooms[token]){req.token=token;req.room=rooms[token];return next()}if(req.query.token)return res.status(401).json({message:'ลิงก์วิดเจตไม่ถูกต้อง'});req.token=key();req.room=rooms[req.token]=newRoom();res.cookie('studio',req.token,{httpOnly:true,sameSite:'lax',secure:req.secure||req.headers['x-forwarded-proto']==='https',maxAge:31536000000});save().catch(console.error);next()}
app.use('/api',room);app.use('/media',room);
const txt=(x,n=220)=>String(x??'').slice(0,n),num=(x,min,max,d)=>Number.isFinite(Number(x))?Math.max(min,Math.min(max,Number(x))):d;
function clean(input){const s={...defaults};for(const k of ['chat','gift','follow','imageVisible','boardVisible'])s[k]=input[k]===true;for(const [k,min,max]of [['rate',.5,1.8],['volume',0,1],['duration',2,15],['alertVolume',0,1],['imageWidth',5,70],['imageX',0,100],['imageY',0,100]])s[k]=num(input[k],min,max,s[k]);s.voice=txt(input.voice,200);if(/^#[a-f\d]{6}$/i.test(input.color))s.color=input.color;for(const k of ['imageId','giftSound','followSound'])s[k]=txt(input[k],80);if([3,5,10].includes(Number(input.boardCount)))s.boardCount=Number(input.boardCount);if(['top','center','bottom'].includes(input.alertPosition))s.alertPosition=input.alertPosition;if(['top-left','top-right','bottom-left'].includes(input.boardPosition))s.boardPosition=input.boardPosition;return s}
export function addEvent(r,raw,test=false){if(!['chat','follow','gift'].includes(raw.type))return;const id=txt(raw.id||randomUUID(),180);if(r.events.some(e=>e.id===id))return;const e={id,type:raw.type,userId:txt(raw.userId||raw.name,100),name:txt(raw.name||'ผู้ชม',100),comment:txt(raw.comment),gift:txt(raw.gift||'ของขวัญ',100),count:Math.floor(num(raw.count,1,100000,1)),unit:Math.floor(num(raw.unit,0,1000000,0)),test,seq:++r.latest,createdAt:Date.now()};r.events.push(e);if(r.events.length>10000)r.events.splice(0,r.events.length-10000);if(e.type==='gift'&&!test){r.totals??={};const p=r.totals[e.userId]||{userId:e.userId,name:e.name,total:0,gifts:0};p.name=e.name;p.total+=e.unit*e.count;p.gifts++;r.totals[e.userId]=p}return e}
app.get('/api/snapshot',(req,res)=>{const r=req.room;res.set('Cache-Control','no-store').json({...r,events:r.events.filter(e=>e.seq>Number(req.query.since||0)).slice(0,100),board:Object.values(r.totals||{}).sort((a,b)=>b.total-a.total).slice(0,10),overlayToken:req.token,totals:undefined})});
app.put('/api/settings',async(req,res)=>{const r=req.room;if(req.body.revision!==r.revision)return res.status(409).json({message:'การตั้งค่าถูกเปลี่ยนจากอีกหน้าต่าง',current:{revision:r.revision}});const s=clean(req.body.settings||{});const refs=[s.imageId,...[s.followSound,s.giftSound].filter(x=>x.startsWith('media:')).map(x=>x.slice(6))].filter(Boolean);if(refs.some(id=>!r.media.some(m=>m.id===id)))return res.status(400).json({message:'ไม่พบไฟล์ที่เลือก'});r.settings=s;r.revision++;await save();res.json({settings:s,revision:r.revision})});
app.post('/api/session',async(req,res)=>{Object.assign(req.room,{session:randomUUID(),username:txt(req.body.username,40),events:[],totals:{},latest:0,revision:req.room.revision+1});await save();res.json({session:req.room.session,revision:req.room.revision})});
app.post('/api/events',async(req,res)=>{if(req.body.session!==req.room.session)return res.status(409).json({message:'รอบไลฟ์เปลี่ยนแล้ว'});if(!Array.isArray(req.body.events)||req.body.events.length>50)return res.sendStatus(400);for(const e of req.body.events)addEvent(req.room,e,true);await save();res.json({ok:true})});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024,files:1}}),types=['image/png','image/jpeg','image/webp','image/gif','audio/mpeg','audio/wav','audio/x-wav','audio/ogg','audio/mp4','audio/x-m4a'];
app.post('/api/upload',upload.single('file'),async(req,res)=>{const f=req.file;if(!f||!types.includes(f.mimetype))return res.status(400).json({message:'เลือกรูปหรือเสียงที่รองรับ ไม่เกิน 8 MB'});if(req.room.media.length>=50)return res.status(400).json({message:'เก็บไฟล์ได้สูงสุด 50 ไฟล์'});const m={id:randomUUID(),name:txt(f.originalname,120),type:f.mimetype};await writeFile(path.join(dataDir,'media',m.id),f.buffer);req.room.media.push(m);await save();res.json(m)});
app.get('/media/:id',async(req,res)=>{const m=req.room.media.find(m=>m.id===req.params.id);if(!m)return res.sendStatus(404);res.type(m.type).set('Cache-Control','private,max-age=86400').send(await readFile(path.join(dataDir,'media',m.id)))});
app.post('/api/live/prepare',(req,res)=>{const username=txt(req.body.username,40).replace(/^@/,'');if(!/^[\w.]{1,40}$/.test(username))return res.status(400).json({message:'ชื่อบัญชีไม่ถูกต้อง'});if(Date.now()-(cooldowns.get(req.token)||0)<10000)return res.status(429).json({message:'รอสักครู่ก่อนเชื่อมต่ออีกครั้ง'});cooldowns.set(req.token,Date.now());const ticket=key();tickets.set(ticket,{token:req.token,username,expires:Date.now()+60000});res.json({ticket,username})});
app.get('/health',(_req,res)=>res.json({ok:true}));app.use(express.static(path.join(root,'public')));app.use((err,req,res,next)=>{console.error(err.message);res.status(err.code==='LIMIT_FILE_SIZE'?413:500).json({message:err.code==='LIMIT_FILE_SIZE'?'ไฟล์ใหญ่เกิน 8 MB':'ดำเนินการไม่ได้ กรุณาลองใหม่'})});
const server=app.listen(process.env.PORT||3000,'0.0.0.0');const wss=new WebSocketServer({noServer:true});
server.on('upgrade',(req,socket,head)=>{const u=new URL(req.url,'http://localhost');const t=tickets.get(u.searchParams.get('ticket'));if(u.pathname!=='/api/live/socket'||!t||t.expires<Date.now()||!req.headers.origin||new URL(req.headers.origin).host!==req.headers.host){socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');return socket.destroy()}tickets.delete(u.searchParams.get('ticket'));wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,t))});
wss.on('connection',(ws,t)=>{const send=data=>{if(ws.readyState===1)ws.send(JSON.stringify(data))};const r=rooms[t.token];let c,started=false;const cleanup=()=>{if(c){c.disconnect();if(connections.get(t.token)===c)connections.delete(t.token);c=null}};ws.on('close',cleanup);ws.on('error',cleanup);ws.on('message',async message=>{if(message.toString()!=='ready'||started)return;started=true;connections.get(t.token)?.disconnect();c=new TikTokLiveConnection(t.username,{enableExtendedGiftInfo:true,processInitialData:false,...(process.env.EULER_API_KEY?{signApiKey:process.env.EULER_API_KEY}:{})});connections.set(t.token,c);const event=(type,d)=>{const normalized=normalizeMessage({type,data:d});if(normalized&&addEvent(r,normalized))save().catch(console.error)};c.on(WebcastEvent.CHAT,d=>event('chat',d));c.on(WebcastEvent.FOLLOW,d=>event('follow',d));c.on(WebcastEvent.GIFT,d=>{event('gift',d)});c.on('error',()=>send({type:'error',message:'บริการรับ TikTok ขัดข้อง ลองเชื่อมต่อใหม่'}));c.on('disconnected',()=>{send({type:'tiktok.disconnect'});ws.close()});try{const info=await c.connect();send({type:'connected',roomId:String(info.roomId)})}catch{send({type:'error',message:'เชื่อมต่อไม่ได้ ตรวจว่าบัญชีกำลังไลฟ์อยู่ บริการเชื่อมต่ออาจจำกัดการใช้งาน'});ws.close(4556);cleanup()}})});
setInterval(()=>{for(const[k,v]of tickets)if(v.expires<Date.now())tickets.delete(k)},60000).unref();
console.log('Stream Gift Studio listening on port '+(process.env.PORT||3000));
